# config/logging.yaml

version: 1
disable_existing_loggers: false

formatters:
  simple:
    format: "%(asctime)s [%(levelname)s] %(name)s: %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
  colored:
    format: "\033[1;32m%(asctime)s\033[0m [%(levelname)s] %(name)s: %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
  verbose:
    format: "%(asctime)s [%(levelname)s] %(name)s [%(process)d:%(thread)d]: %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: colored
    stream: ext://sys.stdout

  file:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: verbose
    filename: logs/platform.log
    maxBytes: 10485760 # 10MB
    backupCount: 5
    encoding: utf8

root:
  level: INFO
  handlers: [console, file]

loggers:
  # Reduce noise from common third-party libraries
  sqlalchemy.engine:
    level: WARNING
    handlers: [console, file]
    propagate: no
  httpx:
    level: WARNING
    handlers: [console, file]
    propagate: no
  # For fine-grained per-module logging, add your own modules here:
  # "application.orchestrators.speech_collection":
  #   level: DEBUG
  #   handlers: [console, file]
  #   propagate: no
